### ISSUE TITLE
Trying to create results in error

### ISSUE THREAD

**Issue by Tosh0kan** [sebastianappler/ffssb#3]
```powershell
D:\01 Libraries\Documents\Coding\Utility Programs [main +12 ~0 -0 !]> py .\ffssb.py create hn https://news.ycombinator.com/ --display-name "Hacker News"
Traceback (most recent call last):
  File "D:\01 Libraries\Documents\Coding\Utility Programs\ffssb.py", line 379, in <module>
    main()
  File "D:\01 Libraries\Documents\Coding\Utility Programs\ffssb.py", line 376, in main
    args.func(args)
  File "D:\01 Libraries\Documents\Coding\Utility Programs\ffssb.py", line 276, in create
    shutil.copytree(baseprofile_path, newprofile_path, symlinks=True, dirs_exist_ok=True)
  File "C:\Users\igor\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 558, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] System could not find the specified path: ''
```

Trying to run the script results in this error. I have all the requirements.

**Comment by sebastianappler** [comment]
It looks like you're running it from Windows? I haven't gotten around to implement it on Windows yet.
Maybe I'll have a go at it at a later point but as of now I would suggest trying it on linux instead.

**Comment by Tosh0kan** [comment]
Then you should make it clear on your README that this is exclusive to Linux. That's basic stuff man. I mean, it's kind of fucking unbelievable that you didn't EXPLICITLY said that in your README. The absolute, overwhelming majority of people do not use Linux, and I won't change to Linux just for this. 

Be better, mate.
